backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends BehaviorsController
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;
use Yii;

use common\models\AccountActivation;
use common\models\GeoCity;
use common\models\GeoCountry;
use common\models\Identity;
// use common\models\LoginForm;
use common\models\ProfileCompany;
use common\models\ProfileCompanyForm;
use common\models\ProfileUserForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;

use yii\base\InvalidParamException;
use yii\helpers\Json;
use yii\helpers\Url;
use frontend\models\SignupForm;
use yii\web\BadRequestHttpException;

use common\models\User;

use frontend\models\ContactForm;
use frontend\models\LoginForm;
use frontend\models\Registration;
use frontend\models\ChangePassword;
use frontend\models\AdminContacts;
use frontend\models\ForgotPassword;

//анкеты
use frontend\models\questionary\General;
use frontend\models\questionary\Agency;
use frontend\models\questionary\Designer;
use frontend\models\questionary\Models;
use frontend\models\questionary\Photographer;

class SiteController extends BehaviorsController
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $contactForm = new ContactForm;
        $contactFormItems = $contactForm->getCategoryQuestions();
        $contactFormOk = FALSE;

        // Отправка формы обратной связи
        if ($contactForm->load(Yii::$app->request->post()) && $contactForm->validate()) {
            if($contactForm->sendEmail()){
                $contactFormOk = TRUE;
            } else{
                die('ошибка при отправке письма');
            }
        }

        //Логин
        $loginForm = new LoginForm();
        if (Yii::$app->user->isGuest){
            if ($loginForm->load(Yii::$app->request->post()) && $loginForm->login()) {
                return $this->redirect(Url::to('site/settings'));
            }
        }

        //Восстановление пароля
        $forgot = new ForgotPassword();
        // if ($forgot->load(Yii::$app->request->post())){
        //     $forgot->forgot();
        // }

        $user = new Registration;
        return $this->render('index', [
            'contactForm'       => $contactForm,
            'contactFormItems'  => $contactFormItems,
            'contactFormOk'     => $contactFormOk,

            'registration' => $user,
            'loginForm' => $loginForm,
            'forgot' => $forgot
        ]);
    }

    // public function actionLogin()
    // {
    //     if (!Yii::$app->user->isGuest) {
    //         return $this->goHome();
    //     }

    //     $model = new LoginForm();
    //     if ($model->load(Yii::$app->request->post()) && $model->login()) {
    //         return $this->redirect('settings');
    //     } else {
    //         // return $this->goBack();

    //         return $this->render('index', [
    //             'loginForm' => $model,
    //         ]);
    //     }
    // }

    public function actionRegistration()
    {
        $user = new Registration;
        if (!($user->load(Yii::$app->request->post()) && $user->registration())) {
            return print_r($user->getErrors());
        }
        return $this->redirect('settings');
    }


    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    //Добавленные страниц
    public function actionQuestionary()
    {
        $general = new General();

        $agency = FALSE;
        $designer = FALSE;
        $models = FALSE;
        $photographer = FALSE;


        // $agency = new Agency();
        // $designer = new Designer();
        // $models = new Models();
        $photographer = new Photographer();

        return $this->render('questionary', [
            'general' => $general,
            'models' => $models,
            'photographer' => $photographer,

            'agency' => $agency,
            'designer' => $designer
            ]);
    }

    public function actionAlbum()
    {
        return $this->render('album');
    }

    public function actionJournal()
    { //Нужно подключить css

        return $this->render('journal');
    }

    // public function actionVisitor()
    // {
    //     // $this->layout('visitor');
    //     // var_dump( $this->layout);die();
    //     return $this->render('settings');   //переработать!!!
    // }

    public function actionSearch()
    {
        return $this->render('search');
    }

    public function actionSettings()
    {
        $msg  = "";
        if ($post = Yii::$app->request->post()) {
            $form = $post['Users'];
            $password_form = ChangePassword::findIdentity(Yii::$app->user->getId());
            $password_form->old_password = $form['old_password'];
            $password_form->new_password = $form['new_password'];
            $password_form->new_password_repeat = $form['repeat_password'];
            if (!$msg = $password_form->change()) {
                $msg = "Пароль успешно изменен";
            }
        }
        return $this->render('settings', [
            'msg' => $msg]);
    }

    public function actionEvents()
    {
        return $this->render('events');
    }

    public function actionVacancies()
    {
        return $this->render('vacancies');
    }

    public function actionSubscription()
    {
        return $this->render('subscription');
    }

    public function actionRecommendations()
    {
        return $this->render('recommendations');
    }

    // public function actionMypage() // переделать по ID
    // {
    //     return $this->render('mypage');
    // }

    public function actionMypage()
    {

    }
























    public function actionSignup($type = null)
    {
        if (!Yii::$app->user->isGuest) { return $this->redirect('/'); }

        // $model = new ProfileUserForm(['scenario' => 'create']);

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     if ($model->status === Identity::STATUS_ACTIVE) {
        //         if (\Yii::$app->getUser()->login($model)) {
        //             return $this->redirect('/site/index');
        //         }
        //     } else {
        //         if ($mail = $model->sendActivationEmail($model)) {
        //             \Yii::$app->session->set(
        //                 'message',
        //                 [
        //                     'type' => 'success',
        //                     'message' => \Yii::t('app', 'Письмо с активацией отправленно на <strong> {email} </strong> (проверьте папку спам).', ['email' => $model->email]),
        //                 ]
        //             );
        //             return $this->redirect(Url::to(['/site/index']));
        //         } else {
        //             \Yii::$app->session->set(
        //                 'message',
        //                 [
        //                     'type' => 'danger',
        //                     'message' => \Yii::t('app', 'Ошибка. Письмо не отправлено.'),
        //                 ]
        //             );
        //             \Yii::error(\Yii::t('app', 'Error. The letter was not sent.'));
        //         }
        //         return $this->refresh();
        //     }
        //     return $this->redirect('/site/index');
        // }
        // return $this->render('signup', ['model' => $model]);
    }

    public function actionCompanySignup()
    {
        if (!Yii::$app->user->isGuest) { return $this->redirect('/'); }

        $model = new ProfileCompanyForm(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->status === Identity::STATUS_ACTIVE) {
                if (\Yii::$app->getUser()->login($model)) {
                    return $this->redirect('/site/index');
                }
            } else {
                if ($mail = $model->sendActivationEmail($model)) {
                    \Yii::$app->session->set(
                        'message',
                        [
                            'type' => 'success',
                            'message' => \Yii::t('app', 'Письмо с активацией отправленно на <strong> {email} </strong> (проверьте папку спам).', ['email' => $model->email]),
                        ]
                    );
                    return $this->redirect(Url::to(['/site/index']));
                } else {
                    \Yii::$app->session->set(
                        'message',
                        [
                            'type' => 'danger',
                            'message' => \Yii::t('app', 'Ошибка. Письмо не отправлено.'),
                        ]
                    );
                    \Yii::error(\Yii::t('app', 'Error. The letter was not sent.'));
                }
                return $this->refresh();
            }
            return $this->redirect('/site/index');
        }
        return $this->render('signup', ['model' => $model]);
    }

    public function actionActivateAccount($key)
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        try {
            $user = new AccountActivation($key);
        }
        catch(\HttpInvalidParamException $e) {
            \Yii::$app->session->set(
                'message',
                [
                    'type'      => 'danger',
                    'message'   => \Yii::t('app', 'Неправильный ключ. Повторите регистрацию.'),
                ]
            );
            throw new BadRequestHttpException($e->getMessage());
        }

        if($user = $user->activateAccount()) {
            /* @var $user Identity */
            \Yii::$app->session->set(
                'message',
                [
                    'type'      => 'success',
                    'message'   => \Yii::t('app', 'Активация прошла успешно.'),
                ]
            );

frontend/views/site/_company-form.php
<?php
/**
 * Created by PhpStorm.
 * User: phpNT - http://phpnt.com
 * Date: 04.09.2016
 * Time: 17:54
 */
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \yii\helpers\Url;
use yii\widgets\MaskedInput;
use dosamigos\typeahead\Bloodhound;
use dosamigos\typeahead\TypeAhead;
use common\models\Identity;
?>
<?php $form = ActiveForm::begin([
    'action' => Url::to(['/site/company-signup']),
    'id' => 'form']) ?>

<div class="col-md-12">
    <?php $model->account_type = Identity::ACCOUNT_COMPANY; ?>
    <?= $form->field($model, 'account_type')
        ->radioList(
            $model->userAccountTypeList,
            [
                'class' => 'radio radio-primary',
                'item' => function ($index, $label, $name, $checked, $value){
                    return '<div class="col-md-6"><input type="radio" id="check-h-'.$index.'" name="'.$name.'" value="'.$value.'" '.($checked ? 'checked' : '').'>
                            <label for="check-h-'.$index.'">'.$label.'</label></div>';
                },
                'onchange' => '
                $.pjax({
                    type: "POST",
                    url: "'.Url::to(['/site/signup']).'",
                    container: "#pjaxBlock",
                    push: true,
                    scrollTo: false
                })
            '
            ])->hint(Yii::t('app', 'Укажите тип аккаунта')); ?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'username')->textInput(['placeholder' => 'Логин']) ?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'name')->textInput(['placeholder' => Yii::t('app', 'Название компании')]) ?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'email')->textInput(['placeholder' => 'Электронная почта'])
        ->hint(Yii::t('app', 'Мы вышлем Вам письмо по электронной почте с ссылкой для активации учетной записи.'))  ?>
</div>
<div class="col-md-12">
    <?php $model->country_id = $model->isNewRecord ? $model->country_id : $model->countryUser ?>
    <?= $form->field($model, 'country_id', [
        'template' => '{label}{input}{error}'])
        ->dropDownList($model->countriesList, [
            'class'  => 'form-control selectpicker',
            'data' => [
                'style' => 'btn-primary',
                'live-search' => true,
                'size' => 7,
            ],
            'onchange' => '
            $.pjax({
                type: "POST",
                url: "'.Url::to(['/geo/set-country']).'",
                data: jQuery("#form").serialize(),
                container: "#pjaxBlock",
                push: false,
                scrollTo: false
            })']) ?>
</div>
<div class="col-md-12">
    <?php
    $engine = new Bloodhound([
        'name' => 'countriesEngine',
        'clientOptions' => [
            'datumTokenizer' => new \yii\web\JsExpression("Bloodhound.tokenizers.obj.whitespace('name')"),
            'queryTokenizer' => new \yii\web\JsExpression("Bloodhound.tokenizers.whitespace"),
            'remote' => [
                'url' => Url::to(['/geo/set-city', 'id'=> $model->country_id, 'q'=>'QRY']),
                'wildcard' => 'QRY'
            ]
        ]
    ]);
    ?>
    <?= $form->field($model, 'city')->widget(
        TypeAhead::className(),
        [
            'options' => ['class' => 'form-control'],
            'engines' => [ $engine ],
            'clientOptions' => [
                'highlight' => true,
                'minLength' => 2,
            ],
            'clientEvents' => [
                'typeahead:selected' => new \yii\web\JsExpression(
                    'function(obj, datum, name) { 
                        $("#city-id").val(datum.id);
                    }'
                ),
            ],
            'dataSets' => [
                [
                    'name' => 'city',
                    'displayKey' => 'city',
                    'source' => $engine->getAdapterScript(),
                    'templates' => [
                        'suggestion' => new \yii\web\JsExpression("function(data){ return '<div class=\"col-xs-12 item-container\"><div class=\"item-header\">' + data.city + '</div><div class=\"item-hint\">' + data.region + '</div></div>'; }"),
                    ],
                ]
            ]
        ]
    );?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'city_id', [
        'template' => '{input}'])->hiddenInput(['id' => 'city-id'])->label(false); ?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'phone',
        [
            'template' => '{label}
                            <div class="input-group">
                                <span class="input-group-addon">+'.$model->calling_code.'</span>{input}
                             </div>
                      <i>{hint}</i>{error}']
    )->widget(MaskedInput::className(),[
        'name' => 'phone',
        'mask' => $model->phone_mask
    ])
        ->hint(Yii::t('app', 'Телефон')) ?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'password')->passwordInput(['placeholder' => Yii::t('app', 'Пароль')]) ?>
</div>

<div class="col-md-12">
    <?= $form->field($model, 'confirm_password')->passwordInput(['placeholder' => Yii::t('app', 'Подтвердите пароль')]) ?>
</div>

<?= Html::hiddenInput('model', 'common\models\ProfileCompanyForm') ?>
<?= Html::hiddenInput('scenario', $model->scenario) ?>
<?= Html::hiddenInput('form', '@frontend/views/site/signup') ?>

<div class="col-md-12">
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Зарегистрировать'), ['class' => 'btn btn-primary block full-width m-b']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

frontend/views/site/album.php
<div class="person-wrapper">
	<div class="album">
		<a href="#add" class="album-add">Добавить</a>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="grid-item">
			<a href="#openModal">
				<img class="grayscale" src="">
			</a>
			<button>Удалить</button>
		</div>
		<div class="pageScroll">
			<p class="scrollLeft"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></p>
			<p class="scrollRight"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></p>
		</div>
	</div>
<!-- ВЫВОД РЕЗУЛЬТАТОВ ПОИСКА ПО ФОТО КОНЕЦ ---------------------------------------------------------------------------------------------->
</div>
<!-- Модальное окно для фото/видео -->
<div id="openModal" class="modal modal-ph">
	<div class="modalWrapper">
		<a href="#close">X</a>
		<img src="http://img.mota.ru/upload/wallpapers/2016/07/26/13/00/49329/mota.ru_2016072621-preview.jpg">
		<div class="modal-btn"><!-- 4 кнопки: фотограф, хозяин фото, модель, альбом в которам размещена фотография -->
			<a href="#photorrapher"></a>
			<a href="#profile"></a>
			<a href="#model"></a>
			<a href="#album"></a>
		</div>
		<p></p><!-- рейтинг фото -->
	</div>
</div>
<div id="add" class="modal modal-ph">
	<div class="modalWrapper">
		<a href="#close">X</a>
		<div class="min-phot">
			<img src="http://img.mota.ru/upload/wallpapers/2016/07/26/13/00/49329/mota.ru_2016072621-preview.jpg">
		</div>
		<form>
			<input type="" name="PhotographerAdd">
		</form>
		<div class="modal-btn"><!-- 4 кнопки: фотограф, хозяин фото, модель, альбом в которам размещена фотография -->
			<a href="#photorrapher"></a>
			<a href="#profile"></a>
			<a href="#model"></a>
			<a href="#album"></a>
		</div>
		<p></p><!-- рейтинг фото -->
	</div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/errors.php
<p> Error </p>

frontend/views/site/events.php
<div class="person-wrapper">
	<div class="j-main">
		<h2>Events</h2>
		<span class="hr"></span>
		<div class="nav-bar">
			<ul class="nav2">
				<li class="active">
					<a href="#fe">FG Events</a>
				</li>
				<li>
					<a href="#me">Members Events</a>
				</li>
			</ul>
		</div>
		<div class="j-section">
			<div class="fe">
				<ul class="nav-fe">
					<li>
						<a href="">All</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Events</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Tenders</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Games&Competitions</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Others</a>
					</li>
				</ul>
			</div>
			<div class="me" style="display: none;">
				<ul class="nav-me">
					<li>
						<a href="">All</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Events</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Tenders</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Games&Competitions</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Others</a>
					</li>
					<li>
						|
					</li>
					<li>
						<a href="">Publish your event</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="j-sidebar">
		<div class="j-t-port">
			<div class="j-t-head">
				Top profile
			</div>
			<div class="j-port-cont">
				<a href="">
					<img src="">
				</a>
			</div>
		</div>
		<div class="j-t-phot">
			<div class="j-t-head">
				Top photo
			</div>
			<div class="j-phot-cont">
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
			</div>
		</div>
	</div>
</div>

frontend/views/site/journal.php
<?= $this->render('_visitor_nav') ?>

<div class="person-wrapper">
	<div class="j-main">
		<h2>Journal</h2>
		<span class="hr"></span>
			<div class="nav-bar">
				<ul class="nav2">
					<li class="active">
						<a href="#fn">FG News</a>
					</li>
					<li>
						<a href="#fs">Fashion Shows</a>
					</li>
					<li>
						<a href="#p">Persons</a>
					</li>
					<li>
						<a href="#fl">Fashion life</a>
					</li>
					<li>
						<a href="#b">Blog</a>
					</li>
				</ul>
			</div>
		<div class="j-item journal_item">
			<div class="j-img">
				<img src="">
			</div>
			<div class="j-txt">
				<h3>Text, Text, Text</h3>
				<p>Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, </p>
				<br>
				<p>Data</p>
			</div>
		</div>
		<div class="j-item journal_item">
			<div class="j-img">
				<img src="">
			</div>
			<div class="j-txt">
				<h3>Text, Text, Text</h3>
				<p>Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, Text, </p>
				<br>
				<p>Data</p>
			</div>
		</div>
	</div>
	<div class="j-sidebar">
		<div class="j-t-port journal_profile">
			<div class="j-t-head">
				Top profile
			</div>
			<div class="j-port-cont">
				<a href="">
					<img src="">
				</a>
			</div>
		</div>
		<div class="j-t-phot journal_photo">
			<div class="j-t-head">
				Top photo
			</div>
			<div class="j-phot-cont">
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
			</div>
		</div>
	</div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Войти');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Пожалуйста заполните следующие поля, чтобы войти.') ?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($model, 'username')->textInput(['placeholder' => Yii::t('app', 'Введите логин, емайл или телефон')]) ?>

            <?= $form->field($model, 'password')->passwordInput(['placeholder' => Yii::t('app', 'Пароль')]) ?>

            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => '<div class="col-xs-12">{input} {label}</div>'
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Войти'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
            <div class="form-group">
                <?= Html::a(Yii::t('app', 'Забыли пароль?'), ['site/request-password-reset']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/mypage.php
<div>This will MyPage</div>

frontend/views/site/requestPasswordResetToken.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = Yii::t('app', 'Запрос на сброс пароля.');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Пожалуйста, введите ваш емайл, чтобы мы отправили ссылку для сброса пароля.') ?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Отправить'), ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/visitor.php
<?php
use yii\helpers\Url;
?>
<link href="/css/customers-style.css" type="text/css" rel="stylesheet">
<!-- Отключение блока с обоями -->
<style type="text/css">
	.c-bg.visitor {
		display: none;
	}
</style>

<?= $this->render('_visitor_nav') ?>